[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
shoot9_solana = "DjeYpeDdifgrngbyx1hD8t6NpidGRpzpn1RdrMaWNgPd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\prama\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
