[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
shoot_9_solana = "AS39cyPiYMfcthVhdJhAq1Bc3jjVoo4a7VRcvFvQuEMP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = '/home/ritikbhatt020/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
